service: SkillBotDefault

provider:
  name: aws
  runtime: nodejs6.10

functions:
  skill:
    handler: lib/src/Index.handler
    environment:
      SKILLBOT_API_TOKEN: DEFAULT_VALUE
    events:
      - alexaSkill
