service: SkillBotDefault

provider:
  name: aws
  runtime: nodejs6.10

functions:
  skill:
    handler: lib/src/Index.handler
    environment:
      SKILLBOT_API_TOKEN: 746561727320696e20746865207261696e0d0a
    events:
      - alexaSkill
